### ISSUE TITLE
You must register this ParseObject subclass before instantiating it.

### ISSUE THREAD

**Issue by raghavendrathippi** [WizTheEngineer/DroidMessenger#1]
Hi, 
I am getting this error while clicking on signup button,and when i remove this line  ParseObject.registerSubclass(MessagingUser.class); signup is working fine. After signing in the messaging is not working.

![screen shot 2015-05-19 at 10 01 48 pm](https://cloud.githubusercontent.com/assets/3061023/7708383/da1f5a4a-fe72-11e4-8cc8-be7bc478ba45.png)

**Comment by WizTheEngineer** [comment]
You need the User class in your Parse database. Can you send me a
screenshot of your Parse dashboard?

**Comment by WizTheEngineer** [comment]
This issue should be fixed with the latest commit. Thanks!
