### ISSUE TITLE
message is not sending , getting Authentication failure  Incorrect Authentication Key message

### ISSUE THREAD

**Issue by sarathandroid** [WizTheEngineer/DroidMessenger#2]
Hi, 
Thanks for your great tutorial. Successfully installed the app but when I am sending message , getting Error sending message:[Error: 112-0] : Authentication Failure. Incorrect Authentication Key . But when I am login again , then getting all the messages I send earlier. Please help me to fix the issue

**Comment by WizTheEngineer** [comment]
Make sure you have a Pubnub application setup and replace the publish and subscribe key.
